# Generated by Django 3.1.12 on 2025-03-24 13:36

import analyzer.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=analyzer.models.dataset_file_path)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel')], max_length=10)),
                ('columns', models.JSONField(default=list)),
                ('dropped_columns', models.JSONField(default=list)),
                ('original_shape', models.CharField(blank=True, max_length=50, null=True)),
                ('current_shape', models.CharField(blank=True, max_length=50, null=True)),
                ('has_preprocessing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Preprocessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_values_strategy', models.CharField(blank=True, choices=[('drop', 'Drop rows with missing values'), ('mean', 'Fill with mean'), ('median', 'Fill with median'), ('mode', 'Fill with mode'), ('constant', 'Fill with constant value')], max_length=20, null=True)),
                ('fill_value', models.CharField(blank=True, max_length=50, null=True)),
                ('encoding_strategy', models.CharField(choices=[('none', 'No encoding'), ('onehot', 'One-Hot Encoding'), ('label', 'Label Encoding')], default='none', max_length=20)),
                ('scaling_strategy', models.CharField(choices=[('none', 'No scaling'), ('minmax', 'Min-Max Scaling'), ('standard', 'Standard Scaling (Z-score)'), ('robust', 'Robust Scaling')], default='none', max_length=20)),
                ('handle_outliers', models.BooleanField(default=False)),
                ('outlier_strategy', models.CharField(blank=True, choices=[('clip', 'Clip outliers'), ('remove', 'Remove outliers')], max_length=20, null=True)),
                ('pca_components', models.PositiveIntegerField(blank=True, null=True)),
                ('feature_selection_strategy', models.CharField(choices=[('none', 'No feature selection'), ('variance', 'Variance Threshold'), ('kbest', 'Select K Best')], default='none', max_length=20)),
                ('k_best_features', models.PositiveIntegerField(blank=True, null=True)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preprocessing', to='analyzer.dataset')),
            ],
        ),
    ]
