# Generated by Django 5.1.7 on 2025-03-26 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnPreprocessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('missing_values_strategy', models.CharField(choices=[('global', 'Use global strategy'), ('drop', 'Drop rows with missing values'), ('mean', 'Fill with mean'), ('median', 'Fill with median'), ('mode', 'Fill with mode'), ('constant', 'Fill with constant value'), ('ffill', 'Forward fill'), ('bfill', 'Backward fill')], default='global', max_length=20)),
                ('fill_value', models.CharField(blank=True, max_length=50, null=True)),
                ('encoding_strategy', models.CharField(choices=[('global', 'Use global strategy'), ('none', 'No encoding'), ('onehot', 'One-Hot Encoding'), ('label', 'Label Encoding')], default='global', max_length=20)),
                ('scaling_strategy', models.CharField(choices=[('global', 'Use global strategy'), ('none', 'No scaling'), ('minmax', 'Min-Max Scaling'), ('standard', 'Standard Scaling (Z-score)'), ('robust', 'Robust Scaling')], default='global', max_length=20)),
                ('handle_outliers', models.BooleanField(default=False)),
                ('outlier_strategy', models.CharField(choices=[('global', 'Use global strategy'), ('clip', 'Clip outliers'), ('remove', 'Remove outliers')], default='global', max_length=20)),
                ('preprocessing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_preprocessings', to='analyzer.preprocessing')),
            ],
            options={
                'unique_together': {('preprocessing', 'column_name')},
            },
        ),
    ]
