# Generated by Django 3.2.23 on 2025-04-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_alter_dataset_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnpreprocessing',
            name='value_replacements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='columnpreprocessing',
            name='outlier_strategy',
            field=models.CharField(choices=[('global', 'Use global strategy'), ('cap', 'Cap outliers'), ('trim', 'Remove outliers')], default='global', max_length=20),
        ),
        migrations.AlterField(
            model_name='preprocessing',
            name='outlier_strategy',
            field=models.CharField(choices=[('global', 'Use global strategy'), ('cap', 'Cap outliers'), ('trim', 'Remove outliers')], default='global', max_length=20),
        ),
    ]
